[package]
name = "graph-neighbor-matching"
version = "0.5.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "MIT"
repository = "https://github.com/mneumann/graph-neighbor-matching"
description = "Graph similarity score using neighbor matching"
keywords = ["graph", "algorithm", "similarity"]

include = ["src/*.rs", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
nalgebra = "0.4.0"
munkres = "0.1.0"
closed01 = "0.3.0"
petgraph = "0.2.2"
