[package]
name = "graph-neighbor-matching"
version = "0.7.1"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "MIT"
repository = "https://github.com/mneumann/graph-neighbor-matching"
description = "Graph similarity score using neighbor matching"
keywords = ["graph", "algorithm", "similarity"]

exclude = ["/target", "/test-helper/target"]
include = ["*.gml", "*.rs", "*.toml", "*.md", "LICENSE"]

[dependencies]
nalgebra = "0.13"
munkres = "0.4"
closed01 = "0.4"
petgraph = "0.4"
approx = "0.1"

[dev-dependencies]

test-helper = {path = "./test-helper", version = "0.1.0"}
