[package]
name = "graph-neighbor-matching"
version = "0.6.2"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "MIT"
repository = "https://github.com/mneumann/graph-neighbor-matching"
description = "Graph similarity score using neighbor matching"
keywords = ["graph", "algorithm", "similarity"]

include = ["src/*.rs", "tests/lib.rs", "tests/graphs/*.gml", "tests/graphs/neat/*.gml", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
nalgebra = "0.5.1"
munkres = "0.3.0"
closed01 = "0.4.0"
petgraph = "0.2.3"

[dev-dependencies]

graph-io-gml = "0.1"
asexp = "0.3"
