[package]
name = "test-helper"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]

[dependencies]

asexp = "0.3"
closed01 = "0.4"
graph-io-gml = "0.2"
graph-neighbor-matching = { path = ".." }
petgraph = "0.4"
