[package]
name = "test-helper"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]

[dependencies]

nalgebra = "0.13"
munkres = "0.3"
closed01 = "0.4"
petgraph = "0.4"
approx = "0.1"
graph-io-gml = "0.2"
asexp = "0.3"
graph-neighbor-matching = {path=".."}
